// <auto-generated />
using System;
using AppService.EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AppService.EF.Migrations
{
    [DbContext(typeof(AppServiceContext))]
    partial class AppServiceContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AppService.Core.AppInfo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AppKey");

                    b.Property<string>("AppName");

                    b.Property<string>("CustomCssUrl");

                    b.Property<string>("Host");

                    b.HasKey("Id");

                    b.ToTable("AppInfos");
                });
#pragma warning restore 612, 618
        }
    }
}
